<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createJsonSchemaFromDocumentType</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBkb2N1bWVudFR5cGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImRv
Y3VtZW50VHlwZSIgKTsNCg0KTmFtZXNwYWNlIG5zID0gTmFtZXNwYWNlLmN1cnJlbnQoKTsNCg0K
TlNOYW1lIG5zTmFtZSA9IE5TTmFtZS5jcmVhdGUoZG9jdW1lbnRUeXBlKTsNCk5TUmVjb3JkIGJh
c2VSZWNvcmQgPSAoTlNSZWNvcmQpIG5zLmdldE5vZGUobnNOYW1lKTsNCg0KSnNvbk9iamVjdCBq
c29uUm9vdCA9IG5ldyBKc29uT2JqZWN0KCk7DQoNCkpzb25PYmplY3Qgcm9vdEZpZWxkcyA9IHBy
b2Nlc3NSZWNvcmRGaWVsZHMoYmFzZVJlY29yZCk7DQpqc29uUm9vdC5hZGRQcm9wZXJ0eSgidHlw
ZSIsICJvYmplY3QiKTsNCmpzb25Sb290LmFkZFByb3BlcnR5KCJhZGRpdGlvbmFsUHJvcGVydGll
cyIsICFiYXNlUmVjb3JkLmlzQ2xvc2VkKCkpOw0KanNvblJvb3QuYWRkKCJwcm9wZXJ0aWVzIiwg
cm9vdEZpZWxkcyk7DQoNCkpzb25BcnJheSByZXF1aXJlZExpc3QgPSBnZXRSZXF1aXJlZEZpZWxk
c0FzQXJyYXkoYmFzZVJlY29yZCk7DQppZihyZXF1aXJlZExpc3QgIT0gbnVsbCl7DQoJanNvblJv
b3QuYWRkKCJyZXF1aXJlZCIsIHJlcXVpcmVkTGlzdCk7DQp9DQoNCklEYXRhVXRpbC5wdXQoIHBp
cGVsaW5lQ3Vyc29yLCAianNvblNjaGVtYSIsIGpzb25Sb290LnRvU3RyaW5nKCkpOw0KCQkNCnBp
cGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCgk=</value>
</Values>
