<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getDocTypeMessagingDetails</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Zwlkb2NUeXBlID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJkb2N1bWVu
dFR5cGUiICk7DQoNCk5TUmVjb3JkIG5zUmVjID0gKE5TUmVjb3JkKSBOYW1lc3BhY2UuY3VycmVu
dCgpLmdldE5vZGUoZG9jVHlwZSk7DQpWYWx1ZXMgZXZlbnREZXNjID0gKFZhbHVlcykgbnNSZWMu
Z2V0VmFsdWVzKCkuZ2V0KCJldmVudERlc2NyaXB0aW9uIik7DQoNClN0cmluZyB1bVBhdGggPSBl
dmVudERlc2MuZ2V0VmFsdWUoImJyb2tlckV2ZW50VHlwZU5hbWUiKS50b1N0cmluZygpOw0KU3Ry
aW5nIG1lc3NhZ2luZ0FsaWFzID0gZXZlbnREZXNjLmdldFZhbHVlKCJhbGlhc05hbWUiKS50b1N0
cmluZygpOw0KdW1QYXRoID0gIi8iICsgdW1QYXRoLnJlcGxhY2UoIjo6IiwgIi8iKTsNCg0KaWYg
KG1lc3NhZ2luZ0FsaWFzLmlzRW1wdHkoKSl7DQoJbWVzc2FnaW5nQWxpYXMgPSAiREVGQVVMVCI7
DQp9DQpJRGF0YVV0aWwucHV0KHBpcGVsaW5lQ3Vyc29yLCAiYWxpYXNOYW1lIiwgbWVzc2FnaW5n
QWxpYXMpOw0KSURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgInVtQ2hhbm5lbFBhdGgiLCB1
bVBhdGgpOw==</value>
</Values>
