<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">packageExists</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlwYWNrYWdlTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAicGFj
a2FnZU5hbWUiKTsNCg0KTmFtZXNwYWNlIG5zID0gTmFtZXNwYWNlLmN1cnJlbnQoKTsNCk5TUGFj
a2FnZVtdIHBhY2thZ2VzID0gbnMuZ2V0QWxsUGFja2FnZXMoKTsNClN0cmluZyBleGlzdHMgPSAi
ZmFsc2UiOw0KDQppbnQgcGFja2FnZUNvdW50ID0gbnMuZ2V0QWxsUGFja2FnZXMoKS5sZW5ndGg7
DQoNCmZvciAoaW50IGo9MDsgaiA8IHBhY2thZ2VDb3VudDsgaisrKXsJCQ0KCWlmKHBhY2thZ2Vz
W2pdLmdldE5hbWUoKS50b1N0cmluZygpLmVxdWFsc0lnbm9yZUNhc2UocGFja2FnZU5hbWUpKSBl
eGlzdHMgPSAidHJ1ZSI7DQp9DQoNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAiZXhp
c3RzIiwgZXhpc3RzKTsNCg0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KCQ==</value>
</Values>
