<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">topicExists</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Zwlkb2N1bWVudFR5cGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImRv
Y3VtZW50VHlwZSIpOw0KDQpOYW1lc3BhY2UgbnMgPSBOYW1lc3BhY2UuY3VycmVudCgpOw0KTlNO
YW1lIG5zTmFtZSA9IE5TTmFtZS5jcmVhdGUoZG9jdW1lbnRUeXBlKTsNCg0KaWYgKG5zLm5vZGVF
eGlzdHMobnNOYW1lKSl7DQoJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJleGlzdHMi
LCAidHJ1ZSIpOw0KfSBlbHNlIHsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgImV4
aXN0cyIsICJmYWxzZSIpOw0KfQ0KDQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
